UPDATE diarydata.diarydata SET year = 2022, month = 6, date = 14, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 기말고사';
UPDATE diarydata.diarydata SET year = 2022, month = 6, date = 27, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 성적열람 기간';
UPDATE diarydata.diarydata SET year = 2022, month = 6, date = 20, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 성적입력 기간';
UPDATE diarydata.diarydata SET year = 2022, month = 2, date = 15, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 수강신청기간 마감';
UPDATE diarydata.diarydata SET year = 2022, month = 2, date = 9, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 수강신청기간 시작';
UPDATE diarydata.diarydata SET year = 2022, month = 3, date = 29, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 수업일수 1/4선';
UPDATE diarydata.diarydata SET year = 2022, month = 4, date = 25, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 수업일수 2/4선';
UPDATE diarydata.diarydata SET year = 2022, month = 5, date = 23, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 수업일수 3/4선';
UPDATE diarydata.diarydata SET year = 2022, month = 6, date = 8, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 정기휴업일 수업결손 보강기간';
UPDATE diarydata.diarydata SET year = 2022, month = 4, date = 20, string = null, `where` = null, icon = 'university.png' WHERE name = '1학기 중간고사';
UPDATE diarydata.diarydata SET year = 2022, month = 12, date = 15, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 기말고사';
UPDATE diarydata.diarydata SET year = 2022, month = 8, date = 23, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 등록기간';
UPDATE diarydata.diarydata SET year = 2022, month = 12, date = 27, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 성적열람 기간';
UPDATE diarydata.diarydata SET year = 2022, month = 12, date = 21, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 성적입력 기간';
UPDATE diarydata.diarydata SET year = 2022, month = 8, date = 5, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 수강신청 시작';
UPDATE diarydata.diarydata SET year = 2022, month = 9, date = 29, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 수업일수 1/4선';
UPDATE diarydata.diarydata SET year = 2022, month = 10, date = 28, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 수업일수 2/4선';
UPDATE diarydata.diarydata SET year = 2022, month = 11, date = 25, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 수업일수 3/4선';
UPDATE diarydata.diarydata SET year = 2022, month = 10, date = 20, string = null, `where` = null, icon = 'university.png' WHERE name = '2학기 중간고사';
UPDATE diarydata.diarydata SET year = 2022, month = 3, date = 2, string = null, `where` = null, icon = 'university.png' WHERE name = '개강';
UPDATE diarydata.diarydata SET year = 2022, month = 3, date = 3, string = null, `where` = null, icon = 'university.png' WHERE name = '수강신청 변경기간';
UPDATE diarydata.diarydata SET year = 2022, month = 1, date = 3, string = null, `where` = null, icon = 'university.png' WHERE name = '시무식';
UPDATE diarydata.diarydata SET year = 2022, month = 2, date = 22, string = null, `where` = null, icon = 'university.png' WHERE name = '신·편입생 수강신청기간 시작';
UPDATE diarydata.diarydata SET year = 2022, month = 2, date = 25, string = null, `where` = null, icon = 'university.png' WHERE name = '신·편입생 수강신청마감 시작';
UPDATE diarydata.diarydata SET year = 2022, month = 2, date = 25, string = null, `where` = null, icon = 'university.png' WHERE name = '전기 학위수여식';
UPDATE diarydata.diarydata SET year = 2022, month = 1, date = 3, string = null, `where` = null, icon = 'university.png' WHERE name = '정시원서접수마감';
UPDATE diarydata.diarydata SET year = 2022, month = 6, date = 20, string = null, `where` = null, icon = 'university.png' WHERE name = '종강';
UPDATE diarydata.diarydata SET year = 2022, month = 12, date = 25, string = null, `where` = null, icon = 'user.png' WHERE name = '크리스마스';
UPDATE diarydata.diarydata SET year = 2022, month = 8, date = 23, string = null, `where` = null, icon = 'university.png' WHERE name = '후기 학위수여식';
UPDATE diarydata.diarydata SET year = 2022, month = 2, date = 1, string = null, `where` = null, icon = 'university.png' WHERE name = '휴·복학원 제출 시작';
